// AUTO-GENERATED from packages/shared — do not hand-edit trade/district/material
// sections. Regenerate via the gen-mobile-constants script whenever the shared
// TypeScript constants change.

class Option {
  final String value;
  final String label;
  const Option(this.value, this.label);
}

extension OptionListLookup on List<Option> {
  String labelFor(String value) {
    for (final option in this) {
      if (option.value == value) return option.label;
    }
    return value;
  }
}

class TradeBranch {
  final String label;
  final List<Option> professions;
  const TradeBranch(this.label, this.professions);
}

class TradeField {
  final String icon;
  final String label;
  final List<TradeBranch> branches;
  const TradeField(this.icon, this.label, this.branches);
}

const List<TradeField> tradeFields = [
  TradeField('🏗️', 'Kaba Yapı', [
    TradeBranch('Kalıp İşleri', [
      Option('KALIP_USTASI', 'Kalıp Ustası'),
      Option('KALIPCI', 'Kalıpçı'),
      Option('KALIP_KALFASI', 'Kalıp Kalfası'),
      Option('AHSAP_KALIP_USTASI', 'Ahşap Kalıp Ustası'),
      Option('SISTEM_KALIP_USTASI', 'Sistem Kalıp Ustası'),
      Option('TUNEL_KALIP_USTASI', 'Tünel Kalıp Ustası'),
      Option('PERDE_KALIP_USTASI', 'Perde Kalıp Ustası'),
      Option('ISKELE_KALIP_USTASI', 'İskele Kalıp Ustası'),
      Option('KALIP_SOKUM_USTASI', 'Kalıp Söküm Ustası'),
    ]),
    TradeBranch('Demir İşleri', [
      Option('DEMIR_USTASI', 'Demir Ustası'),
      Option('DEMIR_BAGLAMA_USTASI', 'Demir Bağlama Ustası'),
      Option('DEMIRCI', 'Demirci'),
      Option('DEMIR_KALFASI', 'Demir Kalfası'),
      Option('DONATI_USTASI', 'Donatı Ustası'),
      Option('HASIR_CELIK_USTASI', 'Hasır Çelik Ustası'),
      Option('FILIZ_EKIMI_USTASI', 'Filiz Ekimi Ustası'),
    ]),
    TradeBranch('Beton İşleri', [
      Option('BETON_USTASI', 'Beton Ustası'),
      Option('BETONCU', 'Betoncu'),
      Option('BETON_VIBRATORCUSU', 'Beton Vibratörcüsü'),
      Option('BETON_POMPA_OPERATORU', 'Beton Pompa Operatörü'),
      Option('BETON_SANTRAL_OPERATORU', 'Beton Santral Operatörü'),
      Option('BETON_PERDAH_USTASI', 'Beton Perdah Ustası'),
      Option('BETON_KESME_USTASI', 'Beton Kesme Ustası'),
      Option('BETON_DELME_USTASI', 'Beton Delme Ustası'),
    ]),
    TradeBranch('Duvar İşleri', [
      Option('DUVAR_USTASI', 'Duvar Ustası'),
      Option('TUGLA_USTASI', 'Tuğla Ustası'),
      Option('GAZBETON_USTASI', 'Gazbeton Ustası'),
      Option('BIMS_USTASI', 'Bims Ustası'),
      Option('TAS_DUVAR_USTASI', 'Taş Duvar Ustası'),
      Option('BRIKET_USTASI', 'Briket Ustası'),
      Option('YIGMA_YAPI_USTASI', 'Yığma Yapı Ustası'),
    ]),
  ]),
  TradeField('🧱', 'İnce Yapı', [
    TradeBranch('Sıva İşleri', [
      Option('SIVA_USTASI', 'Sıva Ustası'),
      Option('KARA_SIVA_USTASI', 'Kara Sıva Ustası'),
      Option('ALCI_SIVA_USTASI', 'Alçı Sıva Ustası'),
      Option('MAKINE_SIVA_USTASI', 'Makine Sıva Ustası'),
      Option('DEKORATIF_SIVA_USTASI', 'Dekoratif Sıva Ustası'),
    ]),
    TradeBranch('Alçı ve Alçıpan', [
      Option('ALCI_USTASI', 'Alçı Ustası'),
      Option('ALCIPAN_USTASI', 'Alçıpan Ustası'),
      Option('ALCIPAN_TAVAN_USTASI', 'Alçıpan Tavan Ustası'),
      Option('BOLME_DUVAR_USTASI', 'Bölme Duvar Ustası'),
      Option('ASMA_TAVAN_USTASI', 'Asma Tavan Ustası'),
      Option('DEKORATIF_ALCI_USTASI', 'Dekoratif Alçı Ustası'),
    ]),
    TradeBranch('Boya', [
      Option('BOYA_USTASI', 'Boya Ustası'),
      Option('BOYACI', 'Boyacı'),
      Option('IC_CEPHE_BOYA_USTASI', 'İç Cephe Boya Ustası'),
      Option('DIS_CEPHE_BOYA_USTASI', 'Dış Cephe Boya Ustası'),
      Option('DEKORATIF_BOYA_USTASI', 'Dekoratif Boya Ustası'),
      Option('EPOKSI_BOYA_USTASI', 'Epoksi Boya Ustası'),
    ]),
    TradeBranch('Zemin ve Kaplama', [
      Option('FAYANS_USTASI', 'Fayans Ustası'),
      Option('SERAMIK_USTASI', 'Seramik Ustası'),
      Option('GRANIT_USTASI', 'Granit Ustası'),
      Option('MERMER_USTASI', 'Mermer Ustası'),
      Option('MOZAIK_USTASI', 'Mozaik Ustası'),
      Option('PARKE_USTASI', 'Parke Ustası'),
      Option('LAMINAT_PARKE_USTASI', 'Laminat Parke Ustası'),
      Option('PVC_ZEMIN_USTASI', 'PVC Zemin Ustası'),
      Option('EPOKSI_ZEMIN_USTASI', 'Epoksi Zemin Ustası'),
      Option('SAP_USTASI', 'Şap Ustası'),
    ]),
  ]),
  TradeField('🏢', 'Dış Cephe', [
    TradeBranch('Mantolama', [
      Option('MANTOLAMA_USTASI', 'Mantolama Ustası'),
      Option('ISI_YALITIM_USTASI', 'Isı Yalıtım Ustası'),
      Option('DIS_CEPHE_USTASI', 'Dış Cephe Ustası'),
      Option('SOVE_USTASI', 'Söve Ustası'),
      Option('FILE_SIVA_USTASI', 'File Sıva Ustası'),
    ]),
    TradeBranch('Cephe Sistemleri', [
      Option('ALUMINYUM_CEPHE_USTASI', 'Alüminyum Cephe Ustası'),
      Option('CAM_CEPHE_USTASI', 'Cam Cephe Ustası'),
      Option('KOMPOZIT_CEPHE_USTASI', 'Kompozit Cephe Ustası'),
      Option('GIYDIRME_CEPHE_USTASI', 'Giydirme Cephe Ustası'),
      Option('PREKAST_CEPHE_USTASI', 'Prekast Cephe Ustası'),
      Option('SILIKON_CEPHE_USTASI', 'Silikon Cephe Ustası'),
    ]),
  ]),
  TradeField('🚰', 'Mekanik Tesisat', [
    TradeBranch('Sıhhi Tesisat', [
      Option('SIHHI_TESISAT_USTASI', 'Sıhhi Tesisat Ustası'),
      Option('SU_TESISATCISI', 'Su Tesisatçısı'),
      Option('TEMIZ_SU_TESISATCISI', 'Temiz Su Tesisatçısı'),
      Option('PIS_SU_TESISATCISI', 'Pis Su Tesisatçısı'),
      Option('YAGMUR_SUYU_TESISATCISI', 'Yağmur Suyu Tesisatçısı'),
      Option('PPRC_TESISAT_USTASI', 'PPRC Tesisat Ustası'),
      Option('PVC_TESISAT_USTASI', 'PVC Tesisat Ustası'),
    ]),
    TradeBranch('Isıtma', [
      Option('KALORIFER_TESISATCISI', 'Kalorifer Tesisatçısı'),
      Option('YERDEN_ISITMA_USTASI', 'Yerden Isıtma Ustası'),
      Option('RADYATOR_USTASI', 'Radyatör Ustası'),
      Option('KAZAN_USTASI', 'Kazan Ustası'),
      Option('ISI_MERKEZI_USTASI', 'Isı Merkezi Ustası'),
    ]),
    TradeBranch('Doğalgaz', [
      Option('DOGALGAZ_TESISAT_USTASI', 'Doğalgaz Tesisat Ustası'),
      Option('DOGALGAZ_KAYNAKCISI', 'Doğalgaz Kaynakçısı'),
      Option('DOGALGAZ_MONTAJ_USTASI', 'Doğalgaz Montaj Ustası'),
      Option('DOGALGAZ_TEKNISYENI', 'Doğalgaz Teknisyeni'),
    ]),
    TradeBranch('Yangın Tesisatı', [
      Option('YANGIN_TESISAT_USTASI', 'Yangın Tesisat Ustası'),
      Option('SPRINKLER_USTASI', 'Sprinkler Ustası'),
      Option('YANGIN_DOLABI_MONTAJ_USTASI', 'Yangın Dolabı Montaj Ustası'),
      Option('YANGIN_HIDROFOR_USTASI', 'Yangın Hidrofor Ustası'),
    ]),
    TradeBranch('Havalandırma', [
      Option('HAVALANDIRMA_USTASI', 'Havalandırma Ustası'),
      Option('KANAL_MONTAJ_USTASI', 'Kanal Montaj Ustası'),
      Option('KLIMA_KANALI_USTASI', 'Klima Kanalı Ustası'),
      Option('ASPIRASYON_USTASI', 'Aspirasyon Ustası'),
      Option('FAN_MONTAJ_USTASI', 'Fan Montaj Ustası'),
    ]),
    TradeBranch('Klima', [
      Option('KLIMA_USTASI', 'Klima Ustası'),
      Option('KLIMA_MONTAJ_USTASI', 'Klima Montaj Ustası'),
      Option('VRF_USTASI', 'VRF Ustası'),
      Option('VRF_TEKNISYENI', 'VRF Teknisyeni'),
      Option('SOGUTMA_TEKNISYENI', 'Soğutma Teknisyeni'),
    ]),
  ]),
  TradeField('⚡', 'Elektrik', [
    TradeBranch('Elektrik Tesisatı', [
      Option('ELEKTRIK_USTASI', 'Elektrik Ustası'),
      Option('ELEKTRIKCI', 'Elektrikçi'),
      Option('ELEKTRIK_TEKNISYENI', 'Elektrik Teknisyeni'),
      Option('ELEKTRIK_TESISATCISI', 'Elektrik Tesisatçısı'),
      Option('KABLO_CEKME_USTASI', 'Kablo Çekme Ustası'),
      Option('ELEKTRIK_MONTAJ_USTASI', 'Elektrik Montaj Ustası'),
    ]),
    TradeBranch('Pano ve Enerji', [
      Option('ELEKTRIK_PANO_USTASI', 'Elektrik Pano Ustası'),
      Option('PANO_MONTAJ_USTASI', 'Pano Montaj Ustası'),
      Option('PANO_TEKNISYENI', 'Pano Teknisyeni'),
      Option('JENERATOR_USTASI', 'Jeneratör Ustası'),
      Option('UPS_TEKNISYENI', 'UPS Teknisyeni'),
    ]),
    TradeBranch('Zayıf Akım', [
      Option('ZAYIF_AKIM_USTASI', 'Zayıf Akım Ustası'),
      Option('DATA_KABLO_USTASI', 'Data Kablo Ustası'),
      Option('TELEFON_TESISATCISI', 'Telefon Tesisatçısı'),
      Option('INTERNET_ALTYAPI_USTASI', 'İnternet Altyapı Ustası'),
      Option('FIBER_OPTIK_USTASI', 'Fiber Optik Ustası'),
    ]),
    TradeBranch('Güvenlik Sistemleri', [
      Option('KAMERA_SISTEMLERI_USTASI', 'Kamera Sistemleri Ustası'),
      Option('ALARM_SISTEMLERI_USTASI', 'Alarm Sistemleri Ustası'),
      Option(
          'YANGIN_ALARM_SISTEMLERI_USTASI', 'Yangın Alarm Sistemleri Ustası'),
      Option(
          'KARTLI_GECIS_SISTEMLERI_USTASI', 'Kartlı Geçiş Sistemleri Ustası'),
      Option('DIAFON_USTASI', 'Diafon Ustası'),
      Option('INTERKOM_USTASI', 'İnterkom Ustası'),
    ]),
  ]),
  TradeField('🪟', 'Doğrama ve Montaj', [
    TradeBranch('PVC ve Alüminyum', [
      Option('PVC_DOGRAMA_USTASI', 'PVC Doğrama Ustası'),
      Option('ALUMINYUM_DOGRAMA_USTASI', 'Alüminyum Doğrama Ustası'),
      Option('ALUMINYUM_CEPHE_USTASI', 'Alüminyum Cephe Ustası'),
      Option('ALUMINYUM_KORKULUK_USTASI', 'Alüminyum Korkuluk Ustası'),
    ]),
    TradeBranch('Cam', [
      Option('CAMCI', 'Camcı'),
      Option('CAM_BALKON_USTASI', 'Cam Balkon Ustası'),
      Option('ISICAM_USTASI', 'Isıcam Ustası'),
      Option('DUSAKABIN_USTASI', 'Duşakabin Ustası'),
      Option('VITRIN_CAMI_USTASI', 'Vitrin Camı Ustası'),
    ]),
    TradeBranch('Kapı ve Pencere', [
      Option('KAPI_USTASI', 'Kapı Ustası'),
      Option('CELIK_KAPI_MONTAJ_USTASI', 'Çelik Kapı Montaj Ustası'),
      Option('IC_KAPI_MONTAJ_USTASI', 'İç Kapı Montaj Ustası'),
      Option('PENCERE_MONTAJ_USTASI', 'Pencere Montaj Ustası'),
      Option('PANJUR_USTASI', 'Panjur Ustası'),
      Option('SINEKLIK_USTASI', 'Sineklik Ustası'),
    ]),
  ]),
  TradeField('🔩', 'Metal ve Çelik İşleri', [
    TradeBranch('Kaynak', [
      Option('KAYNAKCI', 'Kaynakçı'),
      Option('ELEKTRIK_KAYNAKCISI', 'Elektrik Kaynakçısı'),
      Option('GAZALTI_KAYNAKCISI', 'Gazaltı Kaynakçısı'),
      Option('ARGON_KAYNAKCISI', 'Argon Kaynakçısı'),
      Option('OKSIJEN_KAYNAKCISI', 'Oksijen Kaynakçısı'),
      Option('ALUMINYUM_KAYNAKCISI', 'Alüminyum Kaynakçısı'),
    ]),
    TradeBranch('Çelik Konstrüksiyon', [
      Option('CELIK_KONSTRUKSIYON_USTASI', 'Çelik Konstrüksiyon Ustası'),
      Option('CELIK_MONTAJ_USTASI', 'Çelik Montaj Ustası'),
      Option('CELIK_CATI_USTASI', 'Çelik Çatı Ustası'),
      Option('CELIK_MERDIVEN_USTASI', 'Çelik Merdiven Ustası'),
      Option('CELIK_KORKULUK_USTASI', 'Çelik Korkuluk Ustası'),
    ]),
    TradeBranch('Metal İşleri', [
      Option('DEMIR_DOGRAMA_USTASI', 'Demir Doğrama Ustası'),
      Option('FERFORJE_USTASI', 'Ferforje Ustası'),
      Option('KORKULUK_USTASI', 'Korkuluk Ustası'),
      Option('METAL_MONTAJ_USTASI', 'Metal Montaj Ustası'),
    ]),
  ]),
  TradeField('🪚', 'Ahşap ve Marangozluk', [
    TradeBranch('Marangozluk', [
      Option('MARANGOZ', 'Marangoz'),
      Option('AHSAP_USTASI', 'Ahşap Ustası'),
      Option('MOBILYA_USTASI', 'Mobilya Ustası'),
      Option('AHSAP_MONTAJ_USTASI', 'Ahşap Montaj Ustası'),
    ]),
    TradeBranch('Çatı', [
      Option('CATI_USTASI', 'Çatı Ustası'),
      Option('AHSAP_CATI_USTASI', 'Ahşap Çatı Ustası'),
      Option('CATI_KAPLAMA_USTASI', 'Çatı Kaplama Ustası'),
      Option('KIREMIT_USTASI', 'Kiremit Ustası'),
      Option('SHINGLE_USTASI', 'Shingle Ustası'),
      Option('CATI_IZOLASYON_USTASI', 'Çatı İzolasyon Ustası'),
    ]),
    TradeBranch('Dekorasyon', [
      Option('AHSAP_DEKORASYON_USTASI', 'Ahşap Dekorasyon Ustası'),
      Option('PARKE_USTASI', 'Parke Ustası'),
      Option('MERDIVEN_USTASI', 'Merdiven Ustası'),
      Option('AHSAP_MERDIVEN_USTASI', 'Ahşap Merdiven Ustası'),
    ]),
  ]),
  TradeField('💧', 'İzolasyon ve Yalıtım', [
    TradeBranch('Su Yalıtımı', [
      Option('SU_YALITIM_USTASI', 'Su Yalıtım Ustası'),
      Option('MEMBRAN_USTASI', 'Membran Ustası'),
      Option('BITUMLU_MEMBRAN_USTASI', 'Bitümlü Membran Ustası'),
      Option('SURME_IZOLASYON_USTASI', 'Sürme İzolasyon Ustası'),
      Option('TEMEL_IZOLASYON_USTASI', 'Temel İzolasyon Ustası'),
      Option('TERAS_IZOLASYON_USTASI', 'Teras İzolasyon Ustası'),
    ]),
    TradeBranch('Isı Yalıtımı', [
      Option('ISI_YALITIM_USTASI', 'Isı Yalıtım Ustası'),
      Option('MANTOLAMA_USTASI', 'Mantolama Ustası'),
      Option('CATI_IZOLASYON_USTASI', 'Çatı İzolasyon Ustası'),
    ]),
    TradeBranch('Ses Yalıtımı', [
      Option('SES_YALITIM_USTASI', 'Ses Yalıtım Ustası'),
      Option('AKUSTIK_UYGULAMA_USTASI', 'Akustik Uygulama Ustası'),
    ]),
  ]),
  TradeField('🚜', 'Hafriyat ve Altyapı', [
    TradeBranch('Hafriyat', [
      Option('HAFRIYAT_USTASI', 'Hafriyat Ustası'),
      Option('HAFRIYAT_OPERATORU', 'Hafriyat Operatörü'),
      Option('KAZI_USTASI', 'Kazı Ustası'),
      Option('DOLGU_USTASI', 'Dolgu Ustası'),
      Option('TESVIYE_USTASI', 'Tesviye Ustası'),
    ]),
    TradeBranch('Altyapı', [
      Option('KANALIZASYON_USTASI', 'Kanalizasyon Ustası'),
      Option('ALTYAPI_USTASI', 'Altyapı Ustası'),
      Option('DRENAJ_USTASI', 'Drenaj Ustası'),
      Option('YAGMUR_SUYU_ALTYAPI_USTASI', 'Yağmur Suyu Altyapı Ustası'),
      Option('ICME_SUYU_ALTYAPI_USTASI', 'İçme Suyu Altyapı Ustası'),
      Option('MENFEZ_USTASI', 'Menfez Ustası'),
    ]),
    TradeBranch('Yol', [
      Option('ASFALT_USTASI', 'Asfalt Ustası'),
      Option('YOL_YAPIM_USTASI', 'Yol Yapım Ustası'),
      Option('BORDUR_USTASI', 'Bordür Ustası'),
      Option('KALDIRIM_USTASI', 'Kaldırım Ustası'),
      Option('PARKE_TASI_USTASI', 'Parke Taşı Ustası'),
    ]),
  ]),
  TradeField('🚜', 'İş Makineleri ve Operatörler', [
    TradeBranch('Operatörler', [
      Option('EKSKAVATOR_OPERATORU', 'Ekskavatör Operatörü'),
      Option('KEPCE_OPERATORU', 'Kepçe Operatörü'),
      Option('JCB_OPERATORU', 'JCB Operatörü'),
      Option('BOBCAT_OPERATORU', 'Bobcat Operatörü'),
      Option('LODER_OPERATORU', 'Loder Operatörü'),
      Option('DOZER_OPERATORU', 'Dozer Operatörü'),
      Option('GREYDER_OPERATORU', 'Greyder Operatörü'),
      Option('SILINDIR_OPERATORU', 'Silindir Operatörü'),
      Option('FORKLIFT_OPERATORU', 'Forklift Operatörü'),
      Option('MANITOU_OPERATORU', 'Manitou Operatörü'),
      Option('VINC_OPERATORU', 'Vinç Operatörü'),
      Option('MOBIL_VINC_OPERATORU', 'Mobil Vinç Operatörü'),
      Option('KULE_VINC_OPERATORU', 'Kule Vinç Operatörü'),
      Option('BETON_POMPA_OPERATORU', 'Beton Pompa Operatörü'),
      Option('ASFALT_FINISER_OPERATORU', 'Asfalt Finişer Operatörü'),
    ]),
  ]),
  TradeField('👷', 'Teknik ve Şantiye Personeli', [
    TradeBranch('Mühendislik', [
      Option('INSAAT_MUHENDISI', 'İnşaat Mühendisi'),
      Option('MAKINE_MUHENDISI', 'Makine Mühendisi'),
      Option('ELEKTRIK_MUHENDISI', 'Elektrik Mühendisi'),
      Option('HARITA_MUHENDISI', 'Harita Mühendisi'),
      Option('JEOLOJI_MUHENDISI', 'Jeoloji Mühendisi'),
      Option('JEOFIZIK_MUHENDISI', 'Jeofizik Mühendisi'),
    ]),
    TradeBranch('Mimarlık ve Tasarım', [
      Option('MIMAR', 'Mimar'),
      Option('IC_MIMAR', 'İç Mimar'),
      Option('PEYZAJ_MIMARI', 'Peyzaj Mimarı'),
      Option('RESTORATOR', 'Restoratör'),
    ]),
    TradeBranch('Teknik Personel', [
      Option('INSAAT_TEKNIKERI', 'İnşaat Teknikeri'),
      Option('INSAAT_TEKNISYENI', 'İnşaat Teknisyeni'),
      Option('ELEKTRIK_TEKNIKERI', 'Elektrik Teknikeri'),
      Option('MAKINE_TEKNIKERI', 'Makine Teknikeri'),
      Option('HARITA_TEKNIKERI', 'Harita Teknikeri'),
      Option('HARITA_TEKNISYENI', 'Harita Teknisyeni'),
    ]),
    TradeBranch('Şantiye Yönetimi', [
      Option('SANTIYE_SEFI', 'Şantiye Şefi'),
      Option('SANTIYE_MUDURU', 'Şantiye Müdürü'),
      Option('TEKNIK_OFIS_SORUMLUSU', 'Teknik Ofis Sorumlusu'),
      Option('FORMEN', 'Formen'),
      Option('USTABASI', 'Ustabaşı'),
      Option('SAHA_SORUMLUSU', 'Saha Sorumlusu'),
      Option('KALITE_KONTROL_SORUMLUSU', 'Kalite Kontrol Sorumlusu'),
      Option('METRAJ_UZMANI', 'Metraj Uzmanı'),
      Option('HAKEDIS_UZMANI', 'Hakediş Uzmanı'),
    ]),
  ]),
  TradeField('📐', 'Harita ve Ölçüm', [
    TradeBranch('Ölçüm', [
      Option('HARITA_MUHENDISI', 'Harita Mühendisi'),
      Option('HARITA_TEKNIKERI', 'Harita Teknikeri'),
      Option('HARITA_TEKNISYENI', 'Harita Teknisyeni'),
      Option('TOPOGRAF', 'Topograf'),
      Option('OLCUM_ELEMANI', 'Ölçüm Elemanı'),
      Option('GPS_OLCUM_OPERATORU', 'GPS Ölçüm Operatörü'),
      Option('TOTAL_STATION_OPERATORU', 'Total Station Operatörü'),
      Option('NIVELMAN_OPERATORU', 'Nivelman Operatörü'),
      Option('ARAZI_OLCUM_ELEMANI', 'Arazi Ölçüm Elemanı'),
    ]),
  ]),
  TradeField('🚛', 'Nakliye ve Lojistik', [
    TradeBranch('Nakliye', [
      Option('KAMYON_SOFORU', 'Kamyon Şoförü'),
      Option('TIR_SOFORU', 'Tır Şoförü'),
      Option('HAFRIYAT_KAMYONU_SOFORU', 'Hafriyat Kamyonu Şoförü'),
      Option('TRANSMIKSER_SOFORU', 'Transmikser Şoförü'),
      Option('BETON_POMPA_SOFORU', 'Beton Pompa Şoförü'),
      Option('VINCLI_KAMYON_SOFORU', 'Vinçli Kamyon Şoförü'),
      Option('PANELVAN_SOFORU', 'Panelvan Şoförü'),
      Option('SEVKIYAT_PERSONELI', 'Sevkiyat Personeli'),
      Option('DEPO_SORUMLUSU', 'Depo Sorumlusu'),
      Option('LOJISTIK_SORUMLUSU', 'Lojistik Sorumlusu'),
    ]),
  ]),
  TradeField('👷', 'Yardımcı Personel', [
    TradeBranch('Yardımcı Personel', [
      Option('INSAAT_ISCISI', 'İnşaat İşçisi'),
      Option('BEDEN_ISCISI', 'Beden İşçisi'),
      Option('GENEL_INSAAT_ISCISI', 'Genel İnşaat İşçisi'),
      Option('KALFA', 'Kalfa'),
      Option('CIRAK', 'Çırak'),
      Option('YARDIMCI_ELEMAN', 'Yardımcı Eleman'),
      Option('SANTIYE_TEMIZLIK_PERSONELI', 'Şantiye Temizlik Personeli'),
      Option('MALZEME_TASIMA_PERSONELI', 'Malzeme Taşıma Personeli'),
      Option('DEPO_PERSONELI', 'Depo Personeli'),
    ]),
  ]),
  TradeField('🏡', 'Peyzaj ve Çevre Düzenleme', [
    TradeBranch('Peyzaj ve Çevre Düzenleme', [
      Option('PEYZAJ_USTASI', 'Peyzaj Ustası'),
      Option('BAHCE_USTASI', 'Bahçe Ustası'),
      Option('BAHCIVAN', 'Bahçıvan'),
      Option('CIM_UYGULAMA_USTASI', 'Çim Uygulama Ustası'),
      Option('SULAMA_SISTEMI_USTASI', 'Sulama Sistemi Ustası'),
      Option('OTOMATIK_SULAMA_USTASI', 'Otomatik Sulama Ustası'),
      Option('AGAC_BUDAMA_USTASI', 'Ağaç Budama Ustası'),
      Option('TAS_DUVAR_USTASI', 'Taş Duvar Ustası'),
      Option('PEYZAJ_TAS_USTASI', 'Peyzaj Taş Ustası'),
      Option('CEVRE_DUZENLEME_USTASI', 'Çevre Düzenleme Ustası'),
    ]),
  ]),
];

/// Geriye dönük uyumluluk / düz liste (arama, label lookup için).
final List<Option> tradeCategories = [
  for (final field in tradeFields)
    for (final branch in field.branches) ...branch.professions,
];

class MaterialCategory {
  final String icon;
  final String label;
  final List<Option> items;
  const MaterialCategory(this.icon, this.label, this.items);
}

const List<MaterialCategory> materialCategories = [
  MaterialCategory('🪨', 'Temel ve Altyapı Malzemeleri', [
    Option('DOLGU_MALZEMELERI', 'Dolgu malzemeleri'),
    Option('ALT_TEMEL_MALZEMELERI', 'Alt temel malzemeleri'),
    Option('STABILIZE', 'Stabilize'),
    Option('MICIR', 'Mıcır'),
    Option('KIRMATAS', 'Kırmataş'),
    Option('AGREGA', 'Agrega'),
    Option('KUM', 'Kum'),
    Option('CAKIL', 'Çakıl'),
    Option('HAFRIYAT_MALZEMELERI', 'Hafriyat malzemeleri'),
    Option('OCAK_MALZEMELERI', 'Ocak malzemeleri'),
  ]),
  MaterialCategory('🚜', 'Hafriyat ve Nakliye', [
    Option('HAFRIYAT_HIZMETI', 'Hafriyat hizmeti'),
    Option('KAMYON', 'Kamyon'),
    Option('DAMPERLI_KAMYON', 'Damperli kamyon'),
    Option('IS_MAKINESI', 'İş makinesi'),
    Option('EKSKAVATOR', 'Ekskavatör'),
    Option('KEPCE', 'Kepçe'),
    Option('JCB', 'JCB'),
    Option('DOZER', 'Dozer'),
    Option('GREYDER', 'Greyder'),
    Option('SILINDIR', 'Silindir'),
    Option('HAFRIYAT_TASIMA_HIZMETLERI', 'Hafriyat taşıma hizmetleri'),
  ]),
  MaterialCategory('🏗️', 'Kaba Yapı Malzemeleri', [
    Option('INSAAT_DEMIRI', 'İnşaat demiri'),
    Option('HASIR_CELIK', 'Hasır çelik'),
    Option('BETON', 'Beton'),
    Option('CIMENTO', 'Çimento'),
    Option('TUGLA', 'Tuğla'),
    Option('GAZBETON', 'Gazbeton'),
    Option('BIMS', 'Bims'),
    Option('KALIP_MALZEMELERI', 'Kalıp malzemeleri'),
    Option('KERESTE', 'Kereste'),
    Option('PLYWOOD', 'Plywood'),
    Option('ISKELE', 'İskele'),
    Option('KALIP_SISTEMLERI', 'Kalıp sistemleri'),
  ]),
  MaterialCategory('🧱', 'İnce Yapı Malzemeleri', [
    Option('FAYANS', 'Fayans'),
    Option('SERAMIK', 'Seramik'),
    Option('MERMER', 'Mermer'),
    Option('BOYA', 'Boya'),
    Option('ALCI', 'Alçı'),
    Option('ALCIPAN', 'Alçıpan'),
    Option('SAP_MALZEMELERI', 'Şap malzemeleri'),
    Option('YAPISTIRICILAR', 'Yapıştırıcılar'),
    Option('DERZ_MALZEMELERI', 'Derz malzemeleri'),
  ]),
  MaterialCategory('🚰', 'Mekanik Tesisat Malzemeleri', [
    Option('BORU', 'Boru'),
    Option('PPRC', 'PPRC'),
    Option('PVC_MALZEME', 'PVC'),
    Option('VANA', 'Vana'),
    Option('POMPA', 'Pompa'),
    Option('ARMATUR', 'Armatür'),
    Option('RADYATOR', 'Radyatör'),
    Option('YANGIN_TESISATI_MALZEMELERI', 'Yangın tesisatı malzemeleri'),
    Option('HAVALANDIRMA_MALZEMELERI', 'Havalandırma malzemeleri'),
  ]),
  MaterialCategory('⚡', 'Elektrik Malzemeleri', [
    Option('KABLO', 'Kablo'),
    Option('PANO', 'Pano'),
    Option('SIGORTA', 'Sigorta'),
    Option('PRIZ', 'Priz'),
    Option('ANAHTAR', 'Anahtar'),
    Option('AYDINLATMA', 'Aydınlatma'),
    Option('ZAYIF_AKIM_MALZEMELERI', 'Zayıf akım malzemeleri'),
    Option('KAMERA_GUVENLIK_SISTEMLERI', 'Kamera ve güvenlik sistemleri'),
  ]),
];

final List<Option> materialCategoryItems = [
  for (final category in materialCategories) ...category.items,
];

const List<Option> workPreferences = [
  Option('DAILY', 'Günlük iş arıyorum'),
  Option('DAY_WAGE', 'Yevmiyeli iş arıyorum'),
  Option('MONTHLY', 'Aylık iş arıyorum'),
  Option('PERMANENT', 'Sürekli iş arıyorum'),
  Option('PROJECT_BASED', 'Proje bazlı iş arıyorum'),
  Option('TEMPORARY', 'Geçici iş arıyorum'),
  Option('TEAM', 'Ekip olarak iş arıyorum'),
];

const List<Option> listingIntents = [
  Option('PERSONNEL', 'Personel Arıyorum'),
  Option('TEAM', 'Ekip Arıyorum'),
  Option('SUBCONTRACTOR', 'Taşeron Firma Arıyorum'),
  Option('SUB_SUBCONTRACTOR', 'Alt Taşeron Arıyorum'),
  Option('SPECIALIST_FIRM', 'Uzman Firma Arıyorum'),
  Option('SERVICE', 'Hizmet Arıyorum'),
];

const List<Option> employmentTypes = [
  Option('FULL_TIME', 'Tam Zamanlı'),
  Option('PART_TIME', 'Yarı Zamanlı'),
  Option('DAILY', 'Yevmiyeli'),
  Option('CONTRACT', 'Sözleşmeli / Proje Bazlı'),
];

const List<Option> experienceLevels = [
  Option('JUNIOR', '0-2 yıl'),
  Option('MID', '3-6 yıl'),
  Option('SENIOR', '7+ yıl'),
];

const List<Option> wagePeriods = [
  Option('DAILY', 'Günlük'),
  Option('MONTHLY', 'Aylık'),
  Option('HOURLY', 'Saatlik'),
];

const List<Option> priceSubmissionTypes = [
  Option('ACTUAL', 'Gerçekleşen / Ödenen'),
  Option('OFFER', 'Teklif / Beklenti'),
];

class EquipmentCategory {
  final String icon;
  final String label;
  final List<Option> items;
  const EquipmentCategory(this.icon, this.label, this.items);
}

const List<EquipmentCategory> equipmentCategories = [
  EquipmentCategory('🚜', 'Kazı, Hafriyat ve Yükleme', [
    Option('EKSKAVATOR', 'Ekskavatör'),
    Option('MINI_EKSKAVATOR', 'Mini Ekskavatör'),
    Option('PALETLI_EKSKAVATOR', 'Paletli Ekskavatör'),
    Option('LASTIKLI_EKSKAVATOR', 'Lastikli Ekskavatör'),
    Option('BEKOLODER', 'Bekoloder'),
    Option('LODER', 'Loder'),
    Option('MINI_LODER', 'Mini Loder'),
    Option('SKID_STEER', 'Skid Steer'),
    Option('DOZER', 'Dozer'),
    Option('GREYDER', 'Greyder'),
    Option('KANAL_KAZICI', 'Kanal Kazıcı'),
    Option('KAYA_KIRICI', 'Kaya Kırıcı'),
    Option('HIDROLIK_KIRICI', 'Hidrolik Kırıcı'),
    Option('KAYA_DELICI', 'Kaya Delici'),
  ]),
  EquipmentCategory('🚛', 'Taşıma ve Nakliye', [
    Option('HAFRIYAT_KAMYONU', 'Hafriyat Kamyonu'),
    Option('DAMPERLI_KAMYON', 'Damperli Kamyon'),
    Option('KAYA_KAMYONU', 'Kaya Kamyonu'),
    Option('MIKSER', 'Mikser'),
    Option('SU_TANKERI', 'Su Tankeri'),
    Option('LOWBED', 'Lowbed'),
    Option('CEKICI', 'Çekici'),
    Option('FORKLIFT', 'Forklift'),
    Option('TELEHANDLER', 'Telehandler'),
    Option('MANITOU', 'Manitou'),
  ]),
  EquipmentCategory('🏗️', 'Vinç ve Kaldırma', [
    Option('KULE_VINC', 'Kule Vinç'),
    Option('MOBIL_VINC', 'Mobil Vinç'),
    Option('SEPETLI_VINC', 'Sepetli Vinç'),
    Option('ARAC_USTU_VINC', 'Araç Üstü Vinç'),
    Option('TELESKOPIK_VINC', 'Teleskopik Vinç'),
    Option('ORUMCEK_VINC', 'Örümcek Vinç'),
    Option('MINI_VINC', 'Mini Vinç'),
    Option('MALZEME_ASANSORU', 'Malzeme Asansörü'),
    Option('INSAAT_ASANSORU', 'İnşaat Asansörü'),
    Option('MAKASLI_PLATFORM', 'Makaslı Platform'),
    Option('EKLEMLI_PLATFORM', 'Eklemli Platform'),
    Option('PERSONEL_PLATFORMU', 'Personel Platformu'),
  ]),
  EquipmentCategory('🧱', 'Beton ve Şap', [
    Option('BETON_POMPASI', 'Beton Pompası'),
    Option('MINI_BETON_POMPASI', 'Mini Beton Pompası'),
    Option('BETON_MIKSERI', 'Beton Mikseri'),
    Option('BETON_VIBRATORU', 'Beton Vibratörü'),
    Option('LAZERLI_MASTAR', 'Lazerli Mastar'),
    Option('BETON_MASTARI', 'Beton Mastarı'),
    Option('HELIKOPTER_PERDAH_MAKINESI', 'Helikopter Perdah Makinesi'),
    Option('BETON_KESME_MAKINESI', 'Beton Kesme Makinesi'),
    Option('BETON_KIRMA_MAKINESI', 'Beton Kırma Makinesi'),
    Option('SAP_POMPASI', 'Şap Pompası'),
    Option('HARC_MAKINESI', 'Harç Makinesi'),
    Option('SIVA_MAKINESI', 'Sıva Makinesi'),
    Option('ALCI_MAKINESI', 'Alçı Makinesi'),
  ]),
  EquipmentCategory('🏢', 'Kalıp ve İskele', [
    Option('CEPHE_ISKELESI', 'Cephe İskelesi'),
    Option('MOBIL_ISKELE', 'Mobil İskele'),
    Option('KALIP_ISKELESI', 'Kalıp İskelesi'),
    Option('TELESKOPIK_DIKME', 'Teleskopik Dikme'),
    Option('H20_DIKME', 'H20 Dikme'),
    Option('PANEL_KALIP', 'Panel Kalıp'),
    Option('PERDE_KALIP', 'Perde Kalıp'),
    Option('TUNEL_KALIP', 'Tünel Kalıp'),
    Option('KALIP_TASIMA_ARABASI', 'Kalıp Taşıma Arabası'),
    Option('KALIP_EKIPMANLARI', 'Kalıp Ekipmanları'),
  ]),
  EquipmentCategory('🛣️', 'Yol ve Zemin', [
    Option('SILINDIR', 'Silindir'),
    Option('MINI_SILINDIR', 'Mini Silindir'),
    Option('VIBRASYONLU_SILINDIR', 'Vibrasyonlu Silindir'),
    Option('KECI_AYAKLI_SILINDIR', 'Keçi Ayaklı Silindir'),
    Option('ASFALT_SILINDIRI', 'Asfalt Silindiri'),
    Option('ASFALT_FINISERI', 'Asfalt Finişeri'),
    Option('ASFALT_FREZESI', 'Asfalt Frezesi'),
    Option('YOL_SUPURME_MAKINESI', 'Yol Süpürme Makinesi'),
    Option('KOMPAKTOR', 'Kompaktör'),
    Option('TOKMAK', 'Tokmak'),
    Option('ZEMIN_SIKISTIRMA_MAKINESI', 'Zemin Sıkıştırma Makinesi'),
  ]),
  EquipmentCategory('🔨', 'Kırma, Delme ve Kesme', [
    Option('HILTI', 'Hilti'),
    Option('KIRICI', 'Kırıcı'),
    Option('KIRICI_DELICI', 'Kırıcı-Delici'),
    Option('KAROT_MAKINESI', 'Karot Makinesi'),
    Option('BETON_KESME_MAKINESI', 'Beton Kesme Makinesi'),
    Option('DUVAR_KESME_MAKINESI', 'Duvar Kesme Makinesi'),
    Option('ASFALT_KESME_MAKINESI', 'Asfalt Kesme Makinesi'),
    Option('DERZ_KESME_MAKINESI', 'Derz Kesme Makinesi'),
    Option('ELMAS_KESIM_MAKINESI', 'Elmas Kesim Makinesi'),
    Option('MANYETIK_MATKAP', 'Manyetik Matkap'),
  ]),
  EquipmentCategory('🔧', 'Kaynak ve Metal İşleme', [
    Option('ELEKTROT_KAYNAK_MAKINESI', 'Elektrot Kaynak Makinesi'),
    Option('GAZALTI_KAYNAK_MAKINESI', 'Gazaltı Kaynak Makinesi'),
    Option('TIG_KAYNAK_MAKINESI', 'TIG Kaynak Makinesi'),
    Option('MIG_MAG_KAYNAK_MAKINESI', 'MIG/MAG Kaynak Makinesi'),
    Option('KAYNAK_JENERATORU', 'Kaynak Jeneratörü'),
    Option('PLAZMA_KESIM_MAKINESI', 'Plazma Kesim Makinesi'),
    Option('DEMIR_KESME_MAKINESI', 'Demir Kesme Makinesi'),
    Option('DEMIR_BUKME_MAKINESI', 'Demir Bükme Makinesi'),
    Option('PROFIL_KESME_MAKINESI', 'Profil Kesme Makinesi'),
    Option('BORU_BUKME_MAKINESI', 'Boru Bükme Makinesi'),
    Option('BORU_KAYNAK_MAKINESI', 'Boru Kaynak Makinesi'),
  ]),
  EquipmentCategory('⚡', 'Jeneratör, Kompresör ve Enerji', [
    Option('JENERATOR', 'Jeneratör'),
    Option('DIZEL_JENERATOR', 'Dizel Jeneratör'),
    Option('BENZINLI_JENERATOR', 'Benzinli Jeneratör'),
    Option('KAYNAK_JENERATORU', 'Kaynak Jeneratörü'),
    Option('KOMPRESOR', 'Kompresör'),
    Option('HAVA_KOMPRESORU', 'Hava Kompresörü'),
    Option('AYDINLATMA_KULESI', 'Aydınlatma Kulesi'),
    Option('SANTIYE_AYDINLATMASI', 'Şantiye Aydınlatması'),
    Option('ELEKTRIK_PANOSU', 'Elektrik Panosu'),
  ]),
  EquipmentCategory('💧', 'Pompa ve Drenaj', [
    Option('DALGIC_POMPA', 'Dalgıç Pompa'),
    Option('PIS_SU_POMPASI', 'Pis Su Pompası'),
    Option('CAMUR_POMPASI', 'Çamur Pompası'),
    Option('DRENAJ_POMPASI', 'Drenaj Pompası'),
    Option('MOTOPOMP', 'Motopomp'),
    Option('DIZEL_MOTOPOMP', 'Dizel Motopomp'),
    Option('HIDROFOR', 'Hidrofor'),
    Option('SU_TANKI', 'Su Tankı'),
    Option('SU_DEPOSU', 'Su Deposu'),
  ]),
  EquipmentCategory('🌬️', 'Isıtma, Kurutma ve Havalandırma', [
    Option('MAZOTLU_ISITICI', 'Mazotlu Isıtıcı'),
    Option('ELEKTRIKLI_ISITICI', 'Elektrikli Isıtıcı'),
    Option('GAZLI_ISITICI', 'Gazlı Isıtıcı'),
    Option('ENDUSTRIYEL_FAN', 'Endüstriyel Fan'),
    Option('HAVA_UFLEME_MAKINESI', 'Hava Üfleme Makinesi'),
    Option('NEM_ALMA_CIHAZI', 'Nem Alma Cihazı'),
    Option('ENDUSTRIYEL_KURUTUCU', 'Endüstriyel Kurutucu'),
  ]),
  EquipmentCategory('🧹', 'Temizlik', [
    Option('BASINCLI_YIKAMA_MAKINESI', 'Basınçlı Yıkama Makinesi'),
    Option('ENDUSTRIYEL_SUPURGE', 'Endüstriyel Süpürge'),
    Option('ZEMIN_TEMIZLEME_MAKINESI', 'Zemin Temizleme Makinesi'),
    Option('ZEMIN_SILME_MAKINESI', 'Zemin Silme Makinesi'),
    Option('YOL_SUPURME_MAKINESI', 'Yol Süpürme Makinesi'),
  ]),
  EquipmentCategory('📐', 'Ölçüm ve Teknik Ekipman', [
    Option('TOTAL_STATION', 'Total Station'),
    Option('GNSS_GPS', 'GNSS/GPS'),
    Option('NIVO', 'Nivo'),
    Option('LAZER_NIVO', 'Lazer Nivo'),
    Option('ROTATIF_LAZER', 'Rotatif Lazer'),
    Option('LAZER_METRE', 'Lazer Metre'),
    Option('TERMAL_KAMERA', 'Termal Kamera'),
    Option('NEM_OLCER', 'Nem Ölçer'),
    Option('BETON_TEST_CIHAZLARI', 'Beton Test Cihazları'),
    Option('KABLO_BORU_DEDEKTORU', 'Kablo/Boru Dedektörü'),
  ]),
  EquipmentCategory('🏕️', 'Şantiye Ekipmanları', [
    Option('SANTIYE_KONTEYNERI', 'Şantiye Konteyneri'),
    Option('OFIS_KONTEYNERI', 'Ofis Konteyneri'),
    Option('WC_KONTEYNERI', 'WC Konteyneri'),
    Option('DUS_KONTEYNERI', 'Duş Konteyneri'),
    Option('GUVENLIK_KABINI', 'Güvenlik Kabini'),
    Option('YAKIT_TANKI', 'Yakıt Tankı'),
    Option('SU_DEPOSU', 'Su Deposu'),
    Option('SANTIYE_CITI', 'Şantiye Çiti'),
    Option('BARIYER', 'Bariyer'),
    Option('MOBIL_AYDINLATMA', 'Mobil Aydınlatma'),
  ]),
];

final List<Option> equipmentTypes = [
  for (final category in equipmentCategories) ...category.items,
];

const List<Option> materialTypes = [
  Option('DEMIR', 'İnşaat Demiri (TON)'),
  Option('BETON_C30', 'Hazır Beton - C30 (M3)'),
  Option('CIMENTO', 'Çimento (TORBA)'),
  Option('TUGLA', 'Tuğla (ADET)'),
  Option('GAZBETON', 'Gazbeton Blok (M3)'),
  Option('BRIKET', 'Briket / Bims Blok (ADET)'),
  Option('KUM', 'Kum (M3)'),
  Option('AGREGA', 'Agrega / Mıcır (M3)'),
  Option('DOLGU_MALZEMESI', 'Dolgu Malzemesi - Hafriyat/Kırmataş (M3)'),
  Option('HAZIR_HARC', 'Hazır Harç - Sıva/Yapıştırma (TORBA)'),
  Option('ALCI', 'Alçı - Toz (TORBA)'),
  Option('ALCIPAN_LEVHA', 'Alçıpan Levha (M2)'),
  Option('SERAMIK_FAYANS', 'Seramik / Fayans (M2)'),
  Option('PARKE_LAMINAT', 'Parke / Laminat (M2)'),
  Option('CEPHE_BOYASI', 'İç / Dış Cephe Boyası (TENEKE)'),
  Option('MANTOLAMA_LEVHASI', 'Mantolama Levhası - EPS/XPS (M2)'),
  Option('SU_YALITIM_MEMBRANI', 'Su Yalıtım Membranı (M2)'),
  Option('PPRC_BORU', 'PPRC Boru - Sıhhi Tesisat (METRE)'),
  Option('ELEKTRIK_KABLOSU', 'Elektrik Kablosu - NYA/NYM (METRE)'),
];

const List<String> turkishProvinces = [
  'Adana',
  'Adıyaman',
  'Afyonkarahisar',
  'Ağrı',
  'Amasya',
  'Ankara',
  'Antalya',
  'Artvin',
  'Aydın',
  'Balıkesir',
  'Bilecik',
  'Bingöl',
  'Bitlis',
  'Bolu',
  'Burdur',
  'Bursa',
  'Çanakkale',
  'Çankırı',
  'Çorum',
  'Denizli',
  'Diyarbakır',
  'Edirne',
  'Elazığ',
  'Erzincan',
  'Erzurum',
  'Eskişehir',
  'Gaziantep',
  'Giresun',
  'Gümüşhane',
  'Hakkari',
  'Hatay',
  'Isparta',
  'Mersin',
  'İstanbul',
  'İzmir',
  'Kars',
  'Kastamonu',
  'Kayseri',
  'Kırklareli',
  'Kırşehir',
  'Kocaeli',
  'Konya',
  'Kütahya',
  'Malatya',
  'Manisa',
  'Kahramanmaraş',
  'Mardin',
  'Muğla',
  'Muş',
  'Nevşehir',
  'Niğde',
  'Ordu',
  'Rize',
  'Sakarya',
  'Samsun',
  'Siirt',
  'Sinop',
  'Sivas',
  'Tekirdağ',
  'Tokat',
  'Trabzon',
  'Tunceli',
  'Şanlıurfa',
  'Uşak',
  'Van',
  'Yozgat',
  'Zonguldak',
  'Aksaray',
  'Bayburt',
  'Karaman',
  'Kırıkkale',
  'Batman',
  'Şırnak',
  'Bartın',
  'Ardahan',
  'Iğdır',
  'Yalova',
  'Karabük',
  'Kilis',
  'Osmaniye',
  'Düzce',
];

const Map<String, List<String>> districtsByProvince = {
  'Adana': [
    'Aladağ',
    'Ceyhan',
    'Çukurova',
    'Feke',
    'İmamoğlu',
    'Karaisalı',
    'Karataş',
    'Kozan',
    'Pozantı',
    'Saimbeyli',
    'Sarıçam',
    'Seyhan',
    'Tufanbeyli',
    'Yumurtalık',
    'Yüreğir'
  ],
  'Adıyaman': [
    'Besni',
    'Çelikhan',
    'Gerger',
    'Gölbaşı',
    'Kahta',
    'Merkez',
    'Samsat',
    'Sincik',
    'Tut'
  ],
  'Afyonkarahisar': [
    'Başmakçı',
    'Bayat',
    'Bolvadin',
    'Çay',
    'Çobanlar',
    'Dazkırı',
    'Dinar',
    'Emirdağ',
    'Evciler',
    'Hocalar',
    'İhsaniye',
    'İscehisar',
    'Kızılören',
    'Merkez',
    'Sandıklı',
    'Sinanpaşa',
    'Sultandağı',
    'Şuhut'
  ],
  'Ağrı': [
    'Diyadin',
    'Doğubayazıt',
    'Eleşkirt',
    'Hamur',
    'Merkez',
    'Patnos',
    'Taşlıçay',
    'Tutak'
  ],
  'Aksaray': [
    'Ağaçören',
    'Eskil',
    'Gülağaç',
    'Güzelyurt',
    'Merkez',
    'Ortaköy',
    'Sarıyahşi',
    'Sultanhanı'
  ],
  'Amasya': [
    'Göynücek',
    'Gümüşhacıköy',
    'Hamamözü',
    'Merkez',
    'Merzifon',
    'Suluova',
    'Taşova'
  ],
  'Ankara': [
    'Akyurt',
    'Altındağ',
    'Ayaş',
    'Bala',
    'Beypazarı',
    'Çamlıdere',
    'Çankaya',
    'Çubuk',
    'Elmadağ',
    'Etimesgut',
    'Evren',
    'Gölbaşı',
    'Güdül',
    'Haymana',
    'Kahramankazan',
    'Kalecik',
    'Keçiören',
    'Kızılcahamam',
    'Mamak',
    'Nallıhan',
    'Polatlı',
    'Pursaklar',
    'Sincan',
    'Şereflikoçhisar',
    'Yenimahalle'
  ],
  'Antalya': [
    'Akseki',
    'Aksu',
    'Alanya',
    'Demre',
    'Döşemealtı',
    'Elmalı',
    'Finike',
    'Gazipaşa',
    'Gündoğmuş',
    'İbradı',
    'Kaş',
    'Kemer',
    'Kepez',
    'Konyaaltı',
    'Korkuteli',
    'Kumluca',
    'Manavgat',
    'Muratpaşa',
    'Serik'
  ],
  'Ardahan': ['Çıldır', 'Damal', 'Göle', 'Hanak', 'Merkez', 'Posof'],
  'Artvin': [
    'Ardanuç',
    'Arhavi',
    'Borçka',
    'Hopa',
    'Kemalpaşa',
    'Merkez',
    'Murgul',
    'Şavşat',
    'Yusufeli'
  ],
  'Aydın': [
    'Bozdoğan',
    'Buharkent',
    'Çine',
    'Didim',
    'Efeler',
    'Germencik',
    'İncirliova',
    'Karacasu',
    'Karpuzlu',
    'Koçarlı',
    'Köşk',
    'Kuşadası',
    'Kuyucak',
    'Nazilli',
    'Söke',
    'Sultanhisar',
    'Yenipazar'
  ],
  'Balıkesir': [
    'Altıeylül',
    'Ayvalık',
    'Balya',
    'Bandırma',
    'Bigadiç',
    'Burhaniye',
    'Dursunbey',
    'Edremit',
    'Erdek',
    'Gömeç',
    'Gönen',
    'Havran',
    'İvrindi',
    'Karesi',
    'Kepsut',
    'Manyas',
    'Marmara',
    'Savaştepe',
    'Sındırgı',
    'Susurluk'
  ],
  'Bartın': ['Amasra', 'Kurucaşile', 'Merkez', 'Ulus'],
  'Batman': ['Beşiri', 'Gercüş', 'Hasankeyf', 'Kozluk', 'Merkez', 'Sason'],
  'Bayburt': ['Aydıntepe', 'Demirözü', 'Merkez'],
  'Bilecik': [
    'Bozüyük',
    'Gölpazarı',
    'İnhisar',
    'Merkez',
    'Osmaneli',
    'Pazaryeri',
    'Söğüt',
    'Yenipazar'
  ],
  'Bingöl': [
    'Adaklı',
    'Genç',
    'Karlıova',
    'Kiğı',
    'Merkez',
    'Solhan',
    'Yayladere',
    'Yedisu'
  ],
  'Bitlis': [
    'Adilcevaz',
    'Ahlat',
    'Güroymak',
    'Hizan',
    'Merkez',
    'Mutki',
    'Tatvan'
  ],
  'Bolu': [
    'Dörtdivan',
    'Gerede',
    'Göynük',
    'Kıbrıscık',
    'Mengen',
    'Merkez',
    'Mudurnu',
    'Seben',
    'Yeniçağa'
  ],
  'Burdur': [
    'Ağlasun',
    'Altınyayla',
    'Bucak',
    'Çavdır',
    'Çeltikçi',
    'Gölhisar',
    'Karamanlı',
    'Kemer',
    'Merkez',
    'Tefenni',
    'Yeşilova'
  ],
  'Bursa': [
    'Büyükorhan',
    'Gemlik',
    'Gürsu',
    'Harmancık',
    'İnegöl',
    'İznik',
    'Karacabey',
    'Keles',
    'Kestel',
    'Mudanya',
    'Mustafakemalpaşa',
    'Nilüfer',
    'Orhaneli',
    'Orhangazi',
    'Osmangazi',
    'Yenişehir',
    'Yıldırım'
  ],
  'Çanakkale': [
    'Ayvacık',
    'Bayramiç',
    'Biga',
    'Bozcaada',
    'Çan',
    'Eceabat',
    'Ezine',
    'Gelibolu',
    'Gökçeada',
    'Lapseki',
    'Merkez',
    'Yenice'
  ],
  'Çankırı': [
    'Atkaracalar',
    'Bayramören',
    'Çerkeş',
    'Eldivan',
    'Ilgaz',
    'Kızılırmak',
    'Korgun',
    'Kurşunlu',
    'Merkez',
    'Orta',
    'Şabanözü',
    'Yapraklı'
  ],
  'Çorum': [
    'Alaca',
    'Bayat',
    'Boğazkale',
    'Dodurga',
    'İskilip',
    'Kargı',
    'Laçin',
    'Mecitözü',
    'Merkez',
    'Oğuzlar',
    'Ortaköy',
    'Osmancık',
    'Sungurlu',
    'Uğurludağ'
  ],
  'Denizli': [
    'Acıpayam',
    'Babadağ',
    'Baklan',
    'Bekilli',
    'Beyağaç',
    'Bozkurt',
    'Buldan',
    'Çal',
    'Çameli',
    'Çardak',
    'Çivril',
    'Güney',
    'Honaz',
    'Kale',
    'Merkezefendi',
    'Pamukkale',
    'Sarayköy',
    'Serinhisar',
    'Tavas'
  ],
  'Diyarbakır': [
    'Bağlar',
    'Bismil',
    'Çermik',
    'Çınar',
    'Çüngüş',
    'Dicle',
    'Eğil',
    'Ergani',
    'Hani',
    'Hazro',
    'Kayapınar',
    'Kocaköy',
    'Kulp',
    'Lice',
    'Silvan',
    'Sur',
    'Yenişehir'
  ],
  'Düzce': [
    'Akçakoca',
    'Cumayeri',
    'Çilimli',
    'Gölyaka',
    'Gümüşova',
    'Kaynaşlı',
    'Merkez',
    'Yığılca'
  ],
  'Edirne': [
    'Enez',
    'Havsa',
    'İpsala',
    'Keşan',
    'Lalapaşa',
    'Meriç',
    'Merkez',
    'Süloğlu',
    'Uzunköprü'
  ],
  'Elazığ': [
    'Ağın',
    'Alacakaya',
    'Arıcak',
    'Baskil',
    'Karakoçan',
    'Keban',
    'Kovancılar',
    'Maden',
    'Merkez',
    'Palu',
    'Sivrice'
  ],
  'Erzincan': [
    'Çayırlı',
    'İliç',
    'Kemah',
    'Kemaliye',
    'Merkez',
    'Otlukbeli',
    'Refahiye',
    'Tercan',
    'Üzümlü'
  ],
  'Erzurum': [
    'Aşkale',
    'Aziziye',
    'Çat',
    'Hınıs',
    'Horasan',
    'İspir',
    'Karaçoban',
    'Karayazı',
    'Köprüköy',
    'Narman',
    'Oltu',
    'Olur',
    'Palandöken',
    'Pasinler',
    'Pazaryolu',
    'Şenkaya',
    'Tekman',
    'Tortum',
    'Uzundere',
    'Yakutiye'
  ],
  'Eskişehir': [
    'Alpu',
    'Beylikova',
    'Çifteler',
    'Günyüzü',
    'Han',
    'İnönü',
    'Mahmudiye',
    'Mihalgazi',
    'Mihalıççık',
    'Odunpazarı',
    'Sarıcakaya',
    'Seyitgazi',
    'Sivrihisar',
    'Tepebaşı'
  ],
  'Gaziantep': [
    'Araban',
    'İslahiye',
    'Karkamış',
    'Nizip',
    'Nurdağı',
    'Oğuzeli',
    'Şahinbey',
    'Şehitkamil',
    'Yavuzeli'
  ],
  'Giresun': [
    'Alucra',
    'Bulancak',
    'Çamoluk',
    'Çanakçı',
    'Dereli',
    'Doğankent',
    'Espiye',
    'Eynesil',
    'Görele',
    'Güce',
    'Keşap',
    'Merkez',
    'Piraziz',
    'Şebinkarahisar',
    'Tirebolu',
    'Yağlıdere'
  ],
  'Gümüşhane': ['Kelkit', 'Köse', 'Kürtün', 'Merkez', 'Şiran', 'Torul'],
  'Hakkari': ['Çukurca', 'Derecik', 'Merkez', 'Şemdinli', 'Yüksekova'],
  'Hatay': [
    'Altınözü',
    'Antakya',
    'Arsuz',
    'Belen',
    'Defne',
    'Dörtyol',
    'Erzin',
    'Hassa',
    'İskenderun',
    'Kırıkhan',
    'Kumlu',
    'Payas',
    'Reyhanlı',
    'Samandağ',
    'Yayladağı'
  ],
  'Iğdır': ['Aralık', 'Karakoyunlu', 'Merkez', 'Tuzluca'],
  'Isparta': [
    'Aksu',
    'Atabey',
    'Eğirdir',
    'Gelendost',
    'Gönen',
    'Keçiborlu',
    'Merkez',
    'Senirkent',
    'Sütçüler',
    'Şarkikaraağaç',
    'Uluborlu',
    'Yalvaç',
    'Yenişarbademli'
  ],
  'İstanbul': [
    'Adalar',
    'Arnavutköy',
    'Ataşehir',
    'Avcılar',
    'Bağcılar',
    'Bahçelievler',
    'Bakırköy',
    'Başakşehir',
    'Bayrampaşa',
    'Beşiktaş',
    'Beykoz',
    'Beylikdüzü',
    'Beyoğlu',
    'Büyükçekmece',
    'Çatalca',
    'Çekmeköy',
    'Esenler',
    'Esenyurt',
    'Eyüpsultan',
    'Fatih',
    'Gaziosmanpaşa',
    'Güngören',
    'Kadıköy',
    'Kağıthane',
    'Kartal',
    'Küçükçekmece',
    'Maltepe',
    'Pendik',
    'Sancaktepe',
    'Sarıyer',
    'Silivri',
    'Sultanbeyli',
    'Sultangazi',
    'Şile',
    'Şişli',
    'Tuzla',
    'Ümraniye',
    'Üsküdar',
    'Zeytinburnu'
  ],
  'İzmir': [
    'Aliağa',
    'Balçova',
    'Bayındır',
    'Bayraklı',
    'Bergama',
    'Beydağ',
    'Bornova',
    'Buca',
    'Çeşme',
    'Çiğli',
    'Dikili',
    'Foça',
    'Gaziemir',
    'Güzelbahçe',
    'Karabağlar',
    'Karaburun',
    'Karşıyaka',
    'Kemalpaşa',
    'Kınık',
    'Kiraz',
    'Konak',
    'Menderes',
    'Menemen',
    'Narlıdere',
    'Ödemiş',
    'Seferihisar',
    'Selçuk',
    'Tire',
    'Torbalı',
    'Urla'
  ],
  'Kahramanmaraş': [
    'Afşin',
    'Andırın',
    'Çağlayancerit',
    'Dulkadiroğlu',
    'Ekinözü',
    'Elbistan',
    'Göksun',
    'Nurhak',
    'Onikişubat',
    'Pazarcık',
    'Türkoğlu'
  ],
  'Karabük': [
    'Eflani',
    'Eskipazar',
    'Merkez',
    'Ovacık',
    'Safranbolu',
    'Yenice'
  ],
  'Karaman': [
    'Ayrancı',
    'Başyayla',
    'Ermenek',
    'Kazımkarabekir',
    'Merkez',
    'Sarıveliler'
  ],
  'Kars': [
    'Akyaka',
    'Arpaçay',
    'Digor',
    'Kağızman',
    'Merkez',
    'Sarıkamış',
    'Selim',
    'Susuz'
  ],
  'Kastamonu': [
    'Abana',
    'Ağlı',
    'Araç',
    'Azdavay',
    'Bozkurt',
    'Cide',
    'Çatalzeytin',
    'Daday',
    'Devrekani',
    'Doğanyurt',
    'Hanönü',
    'İhsangazi',
    'İnebolu',
    'Küre',
    'Merkez',
    'Pınarbaşı',
    'Seydiler',
    'Şenpazar',
    'Taşköprü',
    'Tosya'
  ],
  'Kayseri': [
    'Akkışla',
    'Bünyan',
    'Develi',
    'Felahiye',
    'Hacılar',
    'İncesu',
    'Kocasinan',
    'Melikgazi',
    'Özvatan',
    'Pınarbaşı',
    'Sarıoğlan',
    'Sarız',
    'Talas',
    'Tomarza',
    'Yahyalı',
    'Yeşilhisar'
  ],
  'Kırıkkale': [
    'Bahşili',
    'Balışeyh',
    'Çelebi',
    'Delice',
    'Karakeçili',
    'Keskin',
    'Merkez',
    'Sulakyurt',
    'Yahşihan'
  ],
  'Kırklareli': [
    'Babaeski',
    'Demirköy',
    'Kofçaz',
    'Lüleburgaz',
    'Merkez',
    'Pehlivanköy',
    'Pınarhisar',
    'Vize'
  ],
  'Kırşehir': [
    'Akçakent',
    'Akpınar',
    'Boztepe',
    'Çiçekdağı',
    'Kaman',
    'Merkez',
    'Mucur'
  ],
  'Kilis': ['Elbeyli', 'Merkez', 'Musabeyli', 'Polateli'],
  'Kocaeli': [
    'Başiskele',
    'Çayırova',
    'Darıca',
    'Derince',
    'Dilovası',
    'Gebze',
    'Gölcük',
    'İzmit',
    'Kandıra',
    'Karamürsel',
    'Kartepe',
    'Körfez'
  ],
  'Konya': [
    'Ahırlı',
    'Akören',
    'Akşehir',
    'Altınekin',
    'Beyşehir',
    'Bozkır',
    'Cihanbeyli',
    'Çeltik',
    'Çumra',
    'Derbent',
    'Derebucak',
    'Doğanhisar',
    'Emirgazi',
    'Ereğli',
    'Güneysınır',
    'Hadim',
    'Halkapınar',
    'Hüyük',
    'Ilgın',
    'Kadınhanı',
    'Karapınar',
    'Karatay',
    'Kulu',
    'Meram',
    'Sarayönü',
    'Selçuklu',
    'Seydişehir',
    'Taşkent',
    'Tuzlukçu',
    'Yalıhüyük',
    'Yunak'
  ],
  'Kütahya': [
    'Altıntaş',
    'Aslanapa',
    'Çavdarhisar',
    'Domaniç',
    'Dumlupınar',
    'Emet',
    'Gediz',
    'Hisarcık',
    'Merkez',
    'Pazarlar',
    'Simav',
    'Şaphane',
    'Tavşanlı'
  ],
  'Malatya': [
    'Akçadağ',
    'Arapgir',
    'Arguvan',
    'Battalgazi',
    'Darende',
    'Doğanşehir',
    'Doğanyol',
    'Hekimhan',
    'Kale',
    'Kuluncak',
    'Pütürge',
    'Yazıhan',
    'Yeşilyurt'
  ],
  'Manisa': [
    'Ahmetli',
    'Akhisar',
    'Alaşehir',
    'Demirci',
    'Gölmarmara',
    'Gördes',
    'Kırkağaç',
    'Köprübaşı',
    'Kula',
    'Salihli',
    'Sarıgöl',
    'Saruhanlı',
    'Selendi',
    'Soma',
    'Şehzadeler',
    'Turgutlu',
    'Yunusemre'
  ],
  'Mardin': [
    'Artuklu',
    'Dargeçit',
    'Derik',
    'Kızıltepe',
    'Mazıdağı',
    'Midyat',
    'Nusaybin',
    'Ömerli',
    'Savur',
    'Yeşilli'
  ],
  'Mersin': [
    'Akdeniz',
    'Anamur',
    'Aydıncık',
    'Bozyazı',
    'Çamlıyayla',
    'Erdemli',
    'Gülnar',
    'Mezitli',
    'Mut',
    'Silifke',
    'Tarsus',
    'Toroslar',
    'Yenişehir'
  ],
  'Muğla': [
    'Bodrum',
    'Dalaman',
    'Datça',
    'Fethiye',
    'Kavaklıdere',
    'Köyceğiz',
    'Marmaris',
    'Menteşe',
    'Milas',
    'Ortaca',
    'Seydikemer',
    'Ula',
    'Yatağan'
  ],
  'Muş': ['Bulanık', 'Hasköy', 'Korkut', 'Malazgirt', 'Merkez', 'Varto'],
  'Nevşehir': [
    'Acıgöl',
    'Avanos',
    'Derinkuyu',
    'Gülşehir',
    'Hacıbektaş',
    'Kozaklı',
    'Merkez',
    'Ürgüp'
  ],
  'Niğde': ['Altunhisar', 'Bor', 'Çamardı', 'Çiftlik', 'Merkez', 'Ulukışla'],
  'Ordu': [
    'Akkuş',
    'Altınordu',
    'Aybastı',
    'Çamaş',
    'Çatalpınar',
    'Çaybaşı',
    'Fatsa',
    'Gölköy',
    'Gülyalı',
    'Gürgentepe',
    'İkizce',
    'Kabadüz',
    'Kabataş',
    'Korgan',
    'Kumru',
    'Mesudiye',
    'Perşembe',
    'Ulubey',
    'Ünye'
  ],
  'Osmaniye': [
    'Bahçe',
    'Düziçi',
    'Hasanbeyli',
    'Kadirli',
    'Merkez',
    'Sumbas',
    'Toprakkale'
  ],
  'Rize': [
    'Ardeşen',
    'Çamlıhemşin',
    'Çayeli',
    'Derepazarı',
    'Fındıklı',
    'Güneysu',
    'Hemşin',
    'İkizdere',
    'İyidere',
    'Kalkandere',
    'Merkez',
    'Pazar'
  ],
  'Sakarya': [
    'Adapazarı',
    'Akyazı',
    'Arifiye',
    'Erenler',
    'Ferizli',
    'Geyve',
    'Hendek',
    'Karapürçek',
    'Karasu',
    'Kaynarca',
    'Kocaali',
    'Pamukova',
    'Sapanca',
    'Serdivan',
    'Söğütlü',
    'Taraklı'
  ],
  'Samsun': [
    '19 Mayıs',
    'Alaçam',
    'Asarcık',
    'Atakum',
    'Ayvacık',
    'Bafra',
    'Canik',
    'Çarşamba',
    'Havza',
    'İlkadım',
    'Kavak',
    'Ladik',
    'Salıpazarı',
    'Tekkeköy',
    'Terme',
    'Vezirköprü',
    'Yakakent'
  ],
  'Siirt': [
    'Baykan',
    'Eruh',
    'Kurtalan',
    'Merkez',
    'Pervari',
    'Şirvan',
    'Tillo'
  ],
  'Sinop': [
    'Ayancık',
    'Boyabat',
    'Dikmen',
    'Durağan',
    'Erfelek',
    'Gerze',
    'Merkez',
    'Saraydüzü',
    'Türkeli'
  ],
  'Sivas': [
    'Akıncılar',
    'Altınyayla',
    'Divriği',
    'Doğanşar',
    'Gemerek',
    'Gölova',
    'Gürün',
    'Hafik',
    'İmranlı',
    'Kangal',
    'Koyulhisar',
    'Merkez',
    'Suşehri',
    'Şarkışla',
    'Ulaş',
    'Yıldızeli',
    'Zara'
  ],
  'Şanlıurfa': [
    'Akçakale',
    'Birecik',
    'Bozova',
    'Ceylanpınar',
    'Eyyübiye',
    'Halfeti',
    'Haliliye',
    'Harran',
    'Hilvan',
    'Karaköprü',
    'Siverek',
    'Suruç',
    'Viranşehir'
  ],
  'Şırnak': [
    'Beytüşşebap',
    'Cizre',
    'Güçlükonak',
    'İdil',
    'Merkez',
    'Silopi',
    'Uludere'
  ],
  'Tekirdağ': [
    'Çerkezköy',
    'Çorlu',
    'Ergene',
    'Hayrabolu',
    'Kapaklı',
    'Malkara',
    'Marmaraereğlisi',
    'Muratlı',
    'Saray',
    'Süleymanpaşa',
    'Şarköy'
  ],
  'Tokat': [
    'Almus',
    'Artova',
    'Başçiftlik',
    'Erbaa',
    'Merkez',
    'Niksar',
    'Pazar',
    'Reşadiye',
    'Sulusaray',
    'Turhal',
    'Yeşilyurt',
    'Zile'
  ],
  'Trabzon': [
    'Akçaabat',
    'Araklı',
    'Arsin',
    'Beşikdüzü',
    'Çarşıbaşı',
    'Çaykara',
    'Dernekpazarı',
    'Düzköy',
    'Hayrat',
    'Köprübaşı',
    'Maçka',
    'Of',
    'Ortahisar',
    'Sürmene',
    'Şalpazarı',
    'Tonya',
    'Vakfıkebir',
    'Yomra'
  ],
  'Tunceli': [
    'Çemişgezek',
    'Hozat',
    'Mazgirt',
    'Merkez',
    'Nazımiye',
    'Ovacık',
    'Pertek',
    'Pülümür'
  ],
  'Uşak': ['Banaz', 'Eşme', 'Karahallı', 'Merkez', 'Sivaslı', 'Ulubey'],
  'Van': [
    'Bahçesaray',
    'Başkale',
    'Çaldıran',
    'Çatak',
    'Edremit',
    'Erciş',
    'Gevaş',
    'Gürpınar',
    'İpekyolu',
    'Muradiye',
    'Özalp',
    'Saray',
    'Tuşba'
  ],
  'Yalova': [
    'Altınova',
    'Armutlu',
    'Çınarcık',
    'Çiftlikköy',
    'Merkez',
    'Termal'
  ],
  'Yozgat': [
    'Akdağmadeni',
    'Aydıncık',
    'Boğazlıyan',
    'Çandır',
    'Çayıralan',
    'Çekerek',
    'Kadışehri',
    'Merkez',
    'Saraykent',
    'Sarıkaya',
    'Sorgun',
    'Şefaatli',
    'Yenifakılı',
    'Yerköy'
  ],
  'Zonguldak': [
    'Alaplı',
    'Çaycuma',
    'Devrek',
    'Ereğli',
    'Gökçebey',
    'Kilimli',
    'Kozlu',
    'Merkez'
  ],
};

List<String> districtsForProvince(String province) =>
    districtsByProvince[province] ?? const [];
